def on_button_pressed_a():
    for index in range(1e+91):
        music.set_volume(255)
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.EIGHTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.EIGHTH))
        music.play_tone(392, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.EIGHTH))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.EIGHTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.EIGHTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.EIGHTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.EIGHTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.EIGHTH))
        music.play_tone(294, music.beat(BeatFraction.QUARTER))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.EIGHTH))
        music.play_tone(330, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.EIGHTH))
        music.play_tone(349, music.beat(BeatFraction.QUARTER))
        music.rest(music.beat(BeatFraction.EIGHTH))
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
input.on_button_pressed(Button.A, on_button_pressed_a)
